name: deploy-dev
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_DEPLOY_HOST_DEV }}
          username: ${{ secrets.FTP_DEPLOY_USERNAME_DEV }}
          password: ${{ secrets.FTP_DEPLOY_PASSWORD_DEV }}
          port: ${{ secrets.FTP_DEPLOY_PORT_DEV }}
          local-dir: "./themes/bob/"
          server-dir: "./wp-content/themes/bob/"
